import {chromium} from 'playwright';
import {readFile, mkdir, writeFile} from 'node:fs/promises';
import path from 'node:path';
const origin = process.env.DEMO_URL || 'http://127.0.0.1:4173';
const out = path.resolve('runs/ui-verification');
await mkdir(out,{recursive:true});
const browser = await chromium.launch({headless:true});
const errors = [];
const page = await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});
page.on('pageerror', error=>errors.push(error.message));
await page.goto(origin,{waitUntil:'networkidle'});
await page.screenshot({path:path.join(out,'dashboard-desktop.png'),fullPage:true});
await page.addScriptTag({content:await readFile(path.resolve('node_modules/axe-core/axe.min.js'),'utf8')});
const audit = await page.evaluate(()=>axe.run({include:[['body']],exclude:[['iframe']]},{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));
const overflow = await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:path.join(out,'dashboard-mobile.png'),fullPage:true});
const mobileOverflow = await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
await writeFile(path.join(out,'dashboard-audit.json'),JSON.stringify({violations:audit.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),errors,desktopOverflow:overflow,mobileOverflow},null,2));
console.log(JSON.stringify({violations:audit.violations.length,errors,desktopOverflow:overflow,mobileOverflow,output:out},null,2));
await browser.close();
if(audit.violations.length||errors.length||overflow||mobileOverflow)process.exitCode=1;
